# action.yml
name: 'Serverless Framework'
description: 'Wraps the Serverless Framework to enable common Serverless commands.'
inputs:
  name:  # id of input
    description: 'Serverless Framework Version'
    required: true
outputs:
  version: # id of output
    description: 'The Serverless Version is:'
runs:
  using: docker
  image: Dockerfile
  env:
    NAME: ${{ inputs.name }}

