name: Build and Test GitHub Action

on: push

jobs:
  serverless-action:
    runs-on: ubuntu-latest
    name: Set serverless Version
    steps:  
      - uses: actions/checkout@v1
      - name: verify actions
        run: |
          ls
      - name: Run a sample Docker container action
        id: sampledockeraction
        uses: ./
        with:
          name: D'Luciano Elfoz de la luz

      - name: Get the output
        shell: bash
        run:  echo ${{ steps.sampledockeraction.outputs.greeting }}


